name: STUDYtable
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pie_chart: ^4.0.1
  tree_view: ^0.0.5
  rflutter_alert: ^1.1.0
  sticky_and_expandable_list: ^0.2.3
  url_launcher: ^5.7.4
  font_awesome_flutter: ^8.10.0
  google_fonts: ^1.1.1
  nice_button: ^0.1.7
  button3d: ^0.1.1
  flutter_svg: ^0.19.1
  nepninja: ^0.0.4
  flutter_animation_progress_bar: ^1.0.6
  firebase_messaging: ^7.0.3
  amplify_core: '<1.0.0'
  amplify_auth_cognito: '<1.0.0'
  custom_radio_grouped_button: ^1.0.6+1
  dropdown_date_picker: ^0.0.3
  image_picker: ^0.6.7+15
  provider: 3.0.0
  http: ^0.12.2
  toast: ^0.1.5


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/cs.jpg
    - lib/assets/images/faceicon.png
    - lib/assets/images/physics.png
    - lib/assets/images/waiting.png
    - lib/assets/images/englishnew.png
    - lib/assets/images/hindinew.png
    - lib/assets/images/mathsnew.png
    - lib/assets/images/studytablenew.png
    - lib/assets/images/chemistrynew.jpg
    - lib/assets/images/login_bottom.png
    - lib/assets/images/main_top.png
    - lib/assets/images/updatesimage.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
